name: Build Artifacts

on:
    push:
        branches: [master]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                include:
                    # WINDOWS
                    - os: ubuntu-latest
                      build_type: windows
                      build_arch: x64
                      gui: cli
                    - os: macos-latest
                      build_type: windows
                      build_arch: arm64
                      gui: cli
                    - os: ubuntu-latest
                      build_type: windows
                      build_arch: x64
                      gui: gui
                    - os: macos-latest
                      build_type: windows
                      build_arch: arm64
                      gui: gui
                    # MACOS
                    - os: ubuntu-latest
                      build_type: macos
                      build_arch: x64
                      gui: cli
                    - os: macos-latest
                      build_type: macos
                      build_arch: arm64
                      gui: cli
                    - os: ubuntu-latest
                      build_type: macos
                      build_arch: x64
                      gui: gui
                    - os: macos-latest
                      build_type: macos
                      build_arch: arm64
                      gui: gui
                    # LINUX
                    - os: ubuntu-latest
                      build_type: linux
                      build_arch: x64
                      gui: cli
                    - os: macos-latest
                      build_type: linux
                      build_arch: arm64
                      gui: cli
                    - os: ubuntu-latest
                      build_type: linux
                      build_arch: x64
                      gui: gui
                    - os: macos-latest
                      build_type: linux
                      build_arch: arm64
                      gui: gui
                    # ALPINE
                    - os: ubuntu-latest
                      build_type: alpine
                      build_arch: x64
                      gui: cli
                    - os: macos-latest
                      build_type: alpine
                      build_arch: arm64
                      gui: cli
                    - os: ubuntu-latest
                      build_type: alpine
                      build_arch: x64
                      gui: gui
                    - os: macos-latest
                      build_type: alpine
                      build_arch: arm64
                      gui: gui
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  check-latest: true
            - name: Install Node modules
              run: |
                  bun install
            - name: Get name and version from package.json
              run: |
                  test -n $(node -p -e "require('./package.json').name") &&
                  test -n $(node -p -e "require('./package.json').version") &&
                  echo PACKAGE_NAME=$(node -p -e "require('./package.json').name") >> $GITHUB_ENV &&
                  echo PACKAGE_VERSION=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV || exit 1
            - name: Make build
              run: bun run build-${{ matrix.build_type }}-${{ matrix.build_arch }}-${{ matrix.gui }}
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: multi-downloader-nx-${{ matrix.build_type }}-${{ matrix.build_arch }}-${{ matrix.gui }}
                  path: |
                      ./lib/_builds/multi-downloader-nx-${{ matrix.build_type }}-${{ matrix.build_arch }}-${{ matrix.gui }}.7z
                      ./lib/_builds/multi-downloader-nx-${{ matrix.build_type }}-${{ matrix.build_arch }}-${{ matrix.gui }}.7z.sha256

